version: "3"
services:
  dashboard_mysql:
    # m1 macの場合コメントアウトを外す
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./db/mysql/store:/var/lib/mysql
      - ./db/mysql/logs:/var/log/mysql
      - ./db/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: dashboard_mysql
    networks:
      - dashboard_net
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${TYPEORM_PORT}:3306
  # dashboard-bff:
  #   build: .
  #   image: kenjishioya/dashboard-bff
  #   depends_on:
  #     - dashboard_mysql
  #   container_name: dashboard-bff
  #   networks:
  #     - dashboard_net
  #   env_file:
  #     - .env
  #   working_dir: '/src/'
  #   volumes:
  #     - ./src:/src
networks:
  dashboard_net:
    name: dashboard_net
    driver: bridge
